import { deviceDiscoveryDto } from './dto/discovery.dto.js';
import {
    changeDeviceRoom,
    control,
    deleteDevice,
    discover,
    getAllDevices,
    getDevice,
    getInfo,
    registerDevice,
    updateDeviceInfo,
} from './smart-home.controller.js';
import {
    changeDeviceRoomDto,
    controlDeviceDto,
    deleteDeviceDto,
    getDeviceDto,
    registerDeviceDto,
    updateDeviceDto,
} from './dto/device.dto.js';

export const SmartHomeRouter = {
    customRouter: true,
    base: '/smart-home',
    routes: [
        {
            name: 'discover',
            description: 'discover devices on network',
            method: 'GET',
            path: '/discover',
            controller: discover,
            dto: deviceDiscoveryDto,
            middlewares: [],
        },
        {
            name: 'getAllDevices',
            description: 'get all devices',
            method: 'GET',
            path: '/devices',
            controller: getAllDevices,
            middlewares: [],
        },
        {
            name: 'registerDevice',
            description: 'register a new device',
            method: 'POST',
            path: '/devices',
            dto: registerDeviceDto,
            controller: registerDevice,
            middlewares: [],
        },
        {
            name: 'control',
            description: 'control device',
            method: 'POST',
            path: '/devices/control',
            dto: controlDeviceDto,
            controller: control,
            middlewares: [],
        },
        {
            name: 'getInfo',
            description: 'get device info',
            method: 'GET',
            path: '/devices/:id/info',
            dto: getDeviceDto,
            controller: getInfo,
            middlewares: [],
        },
        {
            name: 'changeDeviceRoom',
            description: 'changes device room',
            method: 'PATCH',
            path: '/devices/:id/room',
            dto: changeDeviceRoomDto,
            controller: changeDeviceRoom,
            middlewares: [],
        },

        // Generic dynamic routes LAST
        {
            name: 'getDevice',
            description: 'get one device',
            method: 'GET',
            path: '/devices/:id',
            dto: getDeviceDto,
            controller: getDevice,
            middlewares: [],
        },
        {
            name: 'updateDeviceInfo',
            description: 'update existing device info',
            method: 'PATCH',
            path: '/devices/',
            dto: updateDeviceDto,
            controller: updateDeviceInfo,
            middlewares: [],
        },
        {
            name: 'deleteDevice',
            description: 'delete a device by id',
            method: 'DELETE',
            path: '/devices/:id',
            dto: deleteDeviceDto,
            controller: deleteDevice,
            middlewares: [],
        },
    ],
};
