components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "fail"
        error:
          type: object
          properties:
            code:
              type: string
              example: "AUTH_INVALID_TOKEN"
            type:
              type: string
              example: "AuthenticationError"
            message:
              type: string
              example: "The provided token is invalid or expired"
        meta:
          type: object
          properties:
            timestamp:
              type: string
              format: date-time
              example: "2025-09-28T22:00:00Z"